// Seed vocabulary: high-frequency Spanish words (content words, frequency-ordered).
// Function words (de, la, que...) are skipped — they're acquired through sentences, not flashcards.
// Expand with `npm run seed` which upserts this list, or generate more via LLM later.

export type SeedWord = { term: string; translation: string };

export const SPANISH_WORDS: SeedWord[] = [
  { term: "hola", translation: "hello" },
  { term: "gracias", translation: "thank you" },
  { term: "por favor", translation: "please" },
  { term: "sí", translation: "yes" },
  { term: "no", translation: "no" },
  { term: "hoy", translation: "today" },
  { term: "mañana", translation: "tomorrow" },
  { term: "ayer", translation: "yesterday" },
  { term: "tiempo", translation: "time / weather" },
  { term: "día", translation: "day" },
  { term: "noche", translation: "night" },
  { term: "casa", translation: "house" },
  { term: "trabajo", translation: "work / job" },
  { term: "agua", translation: "water" },
  { term: "comida", translation: "food" },
  { term: "café", translation: "coffee" },
  { term: "amigo", translation: "friend" },
  { term: "familia", translation: "family" },
  { term: "dinero", translation: "money" },
  { term: "ciudad", translation: "city" },
  { term: "calle", translation: "street" },
  { term: "coche", translation: "car" },
  { term: "tienda", translation: "store" },
  { term: "libro", translation: "book" },
  { term: "teléfono", translation: "phone" },
  { term: "hombre", translation: "man" },
  { term: "mujer", translation: "woman" },
  { term: "niño", translation: "child" },
  { term: "nombre", translation: "name" },
  { term: "año", translation: "year" },
  { term: "semana", translation: "week" },
  { term: "hora", translation: "hour" },
  { term: "vida", translation: "life" },
  { term: "mundo", translation: "world" },
  { term: "país", translation: "country" },
  { term: "lugar", translation: "place" },
  { term: "cosa", translation: "thing" },
  { term: "persona", translation: "person" },
  { term: "mano", translation: "hand" },
  { term: "ojo", translation: "eye" },
  { term: "cabeza", translation: "head" },
  { term: "corazón", translation: "heart" },
  { term: "puerta", translation: "door" },
  { term: "mesa", translation: "table" },
  { term: "ser", translation: "to be (essence)" },
  { term: "estar", translation: "to be (state/location)" },
  { term: "tener", translation: "to have" },
  { term: "hacer", translation: "to do / make" },
  { term: "ir", translation: "to go" },
  { term: "venir", translation: "to come" },
  { term: "ver", translation: "to see" },
  { term: "dar", translation: "to give" },
  { term: "saber", translation: "to know (facts)" },
  { term: "conocer", translation: "to know (people/places)" },
  { term: "querer", translation: "to want / love" },
  { term: "poder", translation: "to be able to" },
  { term: "decir", translation: "to say" },
  { term: "hablar", translation: "to speak" },
  { term: "comer", translation: "to eat" },
  { term: "beber", translation: "to drink" },
  { term: "vivir", translation: "to live" },
  { term: "trabajar", translation: "to work" },
  { term: "comprar", translation: "to buy" },
  { term: "pagar", translation: "to pay" },
  { term: "buscar", translation: "to look for" },
  { term: "encontrar", translation: "to find" },
  { term: "pensar", translation: "to think" },
  { term: "entender", translation: "to understand" },
  { term: "aprender", translation: "to learn" },
  { term: "leer", translation: "to read" },
  { term: "escribir", translation: "to write" },
  { term: "escuchar", translation: "to listen" },
  { term: "mirar", translation: "to look at" },
  { term: "esperar", translation: "to wait / hope" },
  { term: "necesitar", translation: "to need" },
  { term: "ayudar", translation: "to help" },
  { term: "llamar", translation: "to call" },
  { term: "salir", translation: "to leave / go out" },
  { term: "llegar", translation: "to arrive" },
  { term: "empezar", translation: "to start" },
  { term: "terminar", translation: "to finish" },
  { term: "abrir", translation: "to open" },
  { term: "cerrar", translation: "to close" },
  { term: "dormir", translation: "to sleep" },
  { term: "jugar", translation: "to play" },
  { term: "bueno", translation: "good" },
  { term: "malo", translation: "bad" },
  { term: "grande", translation: "big" },
  { term: "pequeño", translation: "small" },
  { term: "nuevo", translation: "new" },
  { term: "viejo", translation: "old" },
  { term: "feliz", translation: "happy" },
  { term: "triste", translation: "sad" },
  { term: "fácil", translation: "easy" },
  { term: "difícil", translation: "difficult" },
  { term: "rápido", translation: "fast" },
  { term: "lento", translation: "slow" },
  { term: "caliente", translation: "hot" },
  { term: "frío", translation: "cold" },
  { term: "caro", translation: "expensive" },
  { term: "barato", translation: "cheap" },
  { term: "bonito", translation: "pretty" },
  { term: "importante", translation: "important" },
  { term: "cansado", translation: "tired" },
  { term: "aquí", translation: "here" },
  { term: "allí", translation: "there" },
  { term: "cerca", translation: "near" },
  { term: "lejos", translation: "far" },
  { term: "mucho", translation: "a lot" },
  { term: "poco", translation: "a little" },
  { term: "siempre", translation: "always" },
  { term: "nunca", translation: "never" },
  { term: "ahora", translation: "now" },
  { term: "después", translation: "after / later" },
  { term: "antes", translation: "before" },
  { term: "también", translation: "also" },
  { term: "juntos", translation: "together" },
  { term: "otra vez", translation: "again" },
];

export const LANGUAGE_NAMES: Record<string, string> = {
  es: "Spanish",
};
