// Seed vocabulary: 10 languages, each a curated, frequency-ordered mix of
// high-frequency content words, everyday phrases, and common slang.
// Function words (de/la/que-style) are skipped — they're acquired through sentences.
// Non-Latin scripts include a romanized transliteration.
// Expand with `npm run seed`, which upserts these lists.

export type SeedWord = {
  term: string;
  translation: string;
  transliteration?: string;
  kind?: "word" | "phrase" | "slang"; // defaults to "word"
};

export const LANGUAGES: { code: string; name: string; flag: string; rtl?: boolean }[] = [
  { code: "he", name: "Hebrew", flag: "🇮🇱", rtl: true },
  { code: "es", name: "Spanish", flag: "🇪🇸" },
  { code: "fr", name: "French", flag: "🇫🇷" },
  { code: "de", name: "German", flag: "🇩🇪" },
  { code: "it", name: "Italian", flag: "🇮🇹" },
  { code: "pt", name: "Portuguese", flag: "🇧🇷" },
  { code: "ja", name: "Japanese", flag: "🇯🇵" },
  { code: "ko", name: "Korean", flag: "🇰🇷" },
  { code: "zh", name: "Mandarin Chinese", flag: "🇨🇳" },
  { code: "ru", name: "Russian", flag: "🇷🇺" },
];

export const LANGUAGE_NAMES: Record<string, string> = Object.fromEntries(
  LANGUAGES.map((l) => [l.code, l.name])
);

const HEBREW: SeedWord[] = [
  { term: "שלום", translation: "hello / peace", transliteration: "shalom" },
  { term: "תודה", translation: "thank you", transliteration: "toda" },
  { term: "בבקשה", translation: "please / you're welcome", transliteration: "bevakasha" },
  { term: "כן", translation: "yes", transliteration: "ken" },
  { term: "לא", translation: "no", transliteration: "lo" },
  { term: "היום", translation: "today", transliteration: "hayom" },
  { term: "מחר", translation: "tomorrow", transliteration: "machar" },
  { term: "אתמול", translation: "yesterday", transliteration: "etmol" },
  { term: "יום", translation: "day", transliteration: "yom" },
  { term: "לילה", translation: "night", transliteration: "layla" },
  { term: "בית", translation: "house / home", transliteration: "bayit" },
  { term: "עבודה", translation: "work / job", transliteration: "avoda" },
  { term: "מים", translation: "water", transliteration: "mayim" },
  { term: "אוכל", translation: "food", transliteration: "ochel" },
  { term: "קפה", translation: "coffee", transliteration: "kafe" },
  { term: "חבר", translation: "friend", transliteration: "chaver" },
  { term: "משפחה", translation: "family", transliteration: "mishpacha" },
  { term: "כסף", translation: "money", transliteration: "kesef" },
  { term: "עיר", translation: "city", transliteration: "ir" },
  { term: "רחוב", translation: "street", transliteration: "rechov" },
  { term: "מכונית", translation: "car", transliteration: "mechonit" },
  { term: "חנות", translation: "store", transliteration: "chanut" },
  { term: "ספר", translation: "book", transliteration: "sefer" },
  { term: "טלפון", translation: "phone", transliteration: "telefon" },
  { term: "איש", translation: "man", transliteration: "ish" },
  { term: "אישה", translation: "woman", transliteration: "isha" },
  { term: "ילד", translation: "child / boy", transliteration: "yeled" },
  { term: "שם", translation: "name", transliteration: "shem" },
  { term: "שנה", translation: "year", transliteration: "shana" },
  { term: "שבוע", translation: "week", transliteration: "shavua" },
  { term: "שעה", translation: "hour", transliteration: "sha'a" },
  { term: "זמן", translation: "time", transliteration: "zman" },
  { term: "חיים", translation: "life", transliteration: "chayim" },
  { term: "עולם", translation: "world", transliteration: "olam" },
  { term: "מקום", translation: "place", transliteration: "makom" },
  { term: "דבר", translation: "thing", transliteration: "davar" },
  { term: "יד", translation: "hand", transliteration: "yad" },
  { term: "עין", translation: "eye", transliteration: "ayin" },
  { term: "ראש", translation: "head", transliteration: "rosh" },
  { term: "לב", translation: "heart", transliteration: "lev" },
  { term: "יש", translation: "there is / have", transliteration: "yesh" },
  { term: "אין", translation: "there isn't / don't have", transliteration: "ein" },
  { term: "לרצות", translation: "to want", transliteration: "lirtzot" },
  { term: "לאכול", translation: "to eat", transliteration: "le'echol" },
  { term: "לשתות", translation: "to drink", transliteration: "lishtot" },
  { term: "ללכת", translation: "to go / walk", transliteration: "lalechet" },
  { term: "לבוא", translation: "to come", transliteration: "lavo" },
  { term: "לראות", translation: "to see", transliteration: "lir'ot" },
  { term: "לדעת", translation: "to know", transliteration: "lada'at" },
  { term: "לדבר", translation: "to speak", transliteration: "ledaber" },
  { term: "לעבוד", translation: "to work", transliteration: "la'avod" },
  { term: "לקנות", translation: "to buy", transliteration: "liknot" },
  { term: "לחשוב", translation: "to think", transliteration: "lachshov" },
  { term: "להבין", translation: "to understand", transliteration: "lehavin" },
  { term: "ללמוד", translation: "to learn / study", transliteration: "lilmod" },
  { term: "לקרוא", translation: "to read / call", transliteration: "likro" },
  { term: "לכתוב", translation: "to write", transliteration: "lichtov" },
  { term: "לשמוע", translation: "to hear / listen", transliteration: "lishmoa" },
  { term: "לחכות", translation: "to wait", transliteration: "lechakot" },
  { term: "לעזור", translation: "to help", transliteration: "la'azor" },
  { term: "לישון", translation: "to sleep", transliteration: "lishon" },
  { term: "טוב", translation: "good", transliteration: "tov" },
  { term: "רע", translation: "bad", transliteration: "ra" },
  { term: "גדול", translation: "big", transliteration: "gadol" },
  { term: "קטן", translation: "small", transliteration: "katan" },
  { term: "חדש", translation: "new", transliteration: "chadash" },
  { term: "ישן", translation: "old (things)", transliteration: "yashan" },
  { term: "שמח", translation: "happy", transliteration: "sameach" },
  { term: "עצוב", translation: "sad", transliteration: "atzuv" },
  { term: "קל", translation: "easy / light", transliteration: "kal" },
  { term: "קשה", translation: "hard / difficult", transliteration: "kashe" },
  { term: "חם", translation: "hot", transliteration: "cham" },
  { term: "קר", translation: "cold", transliteration: "kar" },
  { term: "יקר", translation: "expensive / dear", transliteration: "yakar" },
  { term: "זול", translation: "cheap", transliteration: "zol" },
  { term: "יפה", translation: "beautiful / nice", transliteration: "yafe" },
  { term: "חשוב", translation: "important", transliteration: "chashuv" },
  { term: "עייף", translation: "tired", transliteration: "ayef" },
  { term: "כאן", translation: "here", transliteration: "kan" },
  { term: "שם (מקום)", translation: "there", transliteration: "sham" },
  { term: "הרבה", translation: "a lot", transliteration: "harbe" },
  { term: "קצת", translation: "a little", transliteration: "ktzat" },
  { term: "תמיד", translation: "always", transliteration: "tamid" },
  { term: "אף פעם", translation: "never", transliteration: "af pa'am" },
  { term: "עכשיו", translation: "now", transliteration: "achshav" },
  { term: "אחר כך", translation: "later / afterwards", transliteration: "achar kach" },
  { term: "גם", translation: "also", transliteration: "gam" },
  { term: "בוקר טוב", translation: "good morning", transliteration: "boker tov", kind: "phrase" },
  { term: "לילה טוב", translation: "good night", transliteration: "layla tov", kind: "phrase" },
  { term: "מה שלומך?", translation: "how are you?", transliteration: "ma shlomcha? (m) / ma shlomech? (f)", kind: "phrase" },
  { term: "מה נשמע?", translation: "what's up? / how's it going?", transliteration: "ma nishma?", kind: "phrase" },
  { term: "סליחה", translation: "sorry / excuse me", transliteration: "slicha", kind: "phrase" },
  { term: "אין בעיה", translation: "no problem", transliteration: "ein be'aya", kind: "phrase" },
  { term: "כמה זה עולה?", translation: "how much does it cost?", transliteration: "kama ze ole?", kind: "phrase" },
  { term: "אני לא מבין", translation: "I don't understand", transliteration: "ani lo mevin (m) / mevina (f)", kind: "phrase" },
  { term: "לאט יותר, בבקשה", translation: "slower, please", transliteration: "le'at yoter, bevakasha", kind: "phrase" },
  { term: "נעים מאוד", translation: "nice to meet you", transliteration: "na'im me'od", kind: "phrase" },
  { term: "בהצלחה", translation: "good luck", transliteration: "behatzlacha", kind: "phrase" },
  { term: "מזל טוב", translation: "congratulations", transliteration: "mazal tov", kind: "phrase" },
  { term: "להתראות", translation: "see you / goodbye", transliteration: "lehitra'ot", kind: "phrase" },
  { term: "אין לי מושג", translation: "I have no idea", transliteration: "ein li musag", kind: "phrase" },
  { term: "סבבה", translation: "cool / alright (slang)", transliteration: "sababa", kind: "slang" },
  { term: "אחלה", translation: "awesome / great (slang)", transliteration: "achla", kind: "slang" },
  { term: "יאללה", translation: "let's go / come on (slang)", transliteration: "yalla", kind: "slang" },
  { term: "בלגן", translation: "mess / chaos (slang)", transliteration: "balagan", kind: "slang" },
  { term: "חבל על הזמן", translation: "amazing / incredible (slang, lit. 'waste of time')", transliteration: "chaval al hazman", kind: "slang" },
  { term: "וואלה", translation: "really? / wow (slang)", transliteration: "walla", kind: "slang" },
  { term: "די", translation: "enough! / stop it", transliteration: "dai", kind: "slang" },
  { term: "כאילו", translation: "like... (filler word)", transliteration: "ke'ilu", kind: "slang" },
  { term: "מגניב", translation: "cool (slang)", transliteration: "magniv", kind: "slang" },
  { term: "סתם", translation: "just kidding / for no reason (slang)", transliteration: "stam", kind: "slang" },
  { term: "קטע", translation: "funny thing / a bit (slang)", transliteration: "keta", kind: "slang" },
  { term: "לא נורא", translation: "no big deal / it's fine", transliteration: "lo nora", kind: "slang" },
  { term: "על הפנים", translation: "terrible (slang, lit. 'on the face')", transliteration: "al hapanim", kind: "slang" },
  { term: "פצצה", translation: "awesome (slang, lit. 'bomb')", transliteration: "ptzatza", kind: "slang" },
];

const SPANISH: SeedWord[] = [
  { term: "hola", translation: "hello" },
  { term: "gracias", translation: "thank you" },
  { term: "por favor", translation: "please" },
  { term: "sí", translation: "yes" },
  { term: "no", translation: "no" },
  { term: "hoy", translation: "today" },
  { term: "mañana", translation: "tomorrow" },
  { term: "ayer", translation: "yesterday" },
  { term: "tiempo", translation: "time / weather" },
  { term: "día", translation: "day" },
  { term: "noche", translation: "night" },
  { term: "casa", translation: "house" },
  { term: "trabajo", translation: "work / job" },
  { term: "agua", translation: "water" },
  { term: "comida", translation: "food" },
  { term: "café", translation: "coffee" },
  { term: "amigo", translation: "friend" },
  { term: "familia", translation: "family" },
  { term: "dinero", translation: "money" },
  { term: "ciudad", translation: "city" },
  { term: "calle", translation: "street" },
  { term: "coche", translation: "car" },
  { term: "tienda", translation: "store" },
  { term: "libro", translation: "book" },
  { term: "teléfono", translation: "phone" },
  { term: "hombre", translation: "man" },
  { term: "mujer", translation: "woman" },
  { term: "niño", translation: "child" },
  { term: "nombre", translation: "name" },
  { term: "año", translation: "year" },
  { term: "semana", translation: "week" },
  { term: "hora", translation: "hour" },
  { term: "vida", translation: "life" },
  { term: "mundo", translation: "world" },
  { term: "país", translation: "country" },
  { term: "lugar", translation: "place" },
  { term: "cosa", translation: "thing" },
  { term: "persona", translation: "person" },
  { term: "mano", translation: "hand" },
  { term: "ojo", translation: "eye" },
  { term: "cabeza", translation: "head" },
  { term: "corazón", translation: "heart" },
  { term: "ser", translation: "to be (essence)" },
  { term: "estar", translation: "to be (state/location)" },
  { term: "tener", translation: "to have" },
  { term: "hacer", translation: "to do / make" },
  { term: "ir", translation: "to go" },
  { term: "venir", translation: "to come" },
  { term: "ver", translation: "to see" },
  { term: "saber", translation: "to know (facts)" },
  { term: "conocer", translation: "to know (people/places)" },
  { term: "querer", translation: "to want / love" },
  { term: "poder", translation: "to be able to" },
  { term: "decir", translation: "to say" },
  { term: "hablar", translation: "to speak" },
  { term: "comer", translation: "to eat" },
  { term: "beber", translation: "to drink" },
  { term: "vivir", translation: "to live" },
  { term: "trabajar", translation: "to work" },
  { term: "comprar", translation: "to buy" },
  { term: "buscar", translation: "to look for" },
  { term: "encontrar", translation: "to find" },
  { term: "pensar", translation: "to think" },
  { term: "entender", translation: "to understand" },
  { term: "aprender", translation: "to learn" },
  { term: "leer", translation: "to read" },
  { term: "escribir", translation: "to write" },
  { term: "escuchar", translation: "to listen" },
  { term: "esperar", translation: "to wait / hope" },
  { term: "necesitar", translation: "to need" },
  { term: "ayudar", translation: "to help" },
  { term: "salir", translation: "to leave / go out" },
  { term: "llegar", translation: "to arrive" },
  { term: "empezar", translation: "to start" },
  { term: "terminar", translation: "to finish" },
  { term: "dormir", translation: "to sleep" },
  { term: "bueno", translation: "good" },
  { term: "malo", translation: "bad" },
  { term: "grande", translation: "big" },
  { term: "pequeño", translation: "small" },
  { term: "nuevo", translation: "new" },
  { term: "viejo", translation: "old" },
  { term: "feliz", translation: "happy" },
  { term: "triste", translation: "sad" },
  { term: "fácil", translation: "easy" },
  { term: "difícil", translation: "difficult" },
  { term: "rápido", translation: "fast" },
  { term: "caliente", translation: "hot" },
  { term: "frío", translation: "cold" },
  { term: "caro", translation: "expensive" },
  { term: "barato", translation: "cheap" },
  { term: "bonito", translation: "pretty" },
  { term: "importante", translation: "important" },
  { term: "cansado", translation: "tired" },
  { term: "aquí", translation: "here" },
  { term: "allí", translation: "there" },
  { term: "mucho", translation: "a lot" },
  { term: "poco", translation: "a little" },
  { term: "siempre", translation: "always" },
  { term: "nunca", translation: "never" },
  { term: "ahora", translation: "now" },
  { term: "después", translation: "after / later" },
  { term: "también", translation: "also" },
  { term: "buenos días", translation: "good morning", kind: "phrase" },
  { term: "buenas noches", translation: "good night", kind: "phrase" },
  { term: "¿cómo estás?", translation: "how are you?", kind: "phrase" },
  { term: "¿qué tal?", translation: "how's it going?", kind: "phrase" },
  { term: "lo siento", translation: "I'm sorry", kind: "phrase" },
  { term: "no hay problema", translation: "no problem", kind: "phrase" },
  { term: "¿cuánto cuesta?", translation: "how much does it cost?", kind: "phrase" },
  { term: "no entiendo", translation: "I don't understand", kind: "phrase" },
  { term: "más despacio, por favor", translation: "slower, please", kind: "phrase" },
  { term: "mucho gusto", translation: "nice to meet you", kind: "phrase" },
  { term: "buena suerte", translation: "good luck", kind: "phrase" },
  { term: "hasta luego", translation: "see you later", kind: "phrase" },
  { term: "ni idea", translation: "no idea", kind: "phrase" },
  { term: "guay", translation: "cool (Spain slang)", kind: "slang" },
  { term: "chévere", translation: "cool (Latin America slang)", kind: "slang" },
  { term: "vale", translation: "okay (Spain)", kind: "slang" },
  { term: "tío / tía", translation: "dude / girl (Spain slang, lit. uncle/aunt)", kind: "slang" },
  { term: "qué padre", translation: "how cool (Mexico slang)", kind: "slang" },
  { term: "no pasa nada", translation: "no worries / it's fine", kind: "slang" },
  { term: "¡órale!", translation: "wow! / come on! (Mexico slang)", kind: "slang" },
  { term: "flipar", translation: "to freak out / be amazed (Spain slang)", kind: "slang" },
];

const FRENCH: SeedWord[] = [
  { term: "bonjour", translation: "hello / good morning" },
  { term: "merci", translation: "thank you" },
  { term: "s'il vous plaît", translation: "please" },
  { term: "oui", translation: "yes" },
  { term: "non", translation: "no" },
  { term: "aujourd'hui", translation: "today" },
  { term: "demain", translation: "tomorrow" },
  { term: "hier", translation: "yesterday" },
  { term: "temps", translation: "time / weather" },
  { term: "jour", translation: "day" },
  { term: "nuit", translation: "night" },
  { term: "maison", translation: "house" },
  { term: "travail", translation: "work / job" },
  { term: "eau", translation: "water" },
  { term: "nourriture", translation: "food" },
  { term: "café", translation: "coffee" },
  { term: "ami", translation: "friend" },
  { term: "famille", translation: "family" },
  { term: "argent", translation: "money" },
  { term: "ville", translation: "city" },
  { term: "rue", translation: "street" },
  { term: "voiture", translation: "car" },
  { term: "magasin", translation: "store" },
  { term: "livre", translation: "book" },
  { term: "homme", translation: "man" },
  { term: "femme", translation: "woman" },
  { term: "enfant", translation: "child" },
  { term: "nom", translation: "name" },
  { term: "année", translation: "year" },
  { term: "semaine", translation: "week" },
  { term: "heure", translation: "hour" },
  { term: "vie", translation: "life" },
  { term: "monde", translation: "world" },
  { term: "chose", translation: "thing" },
  { term: "main", translation: "hand" },
  { term: "cœur", translation: "heart" },
  { term: "être", translation: "to be" },
  { term: "avoir", translation: "to have" },
  { term: "faire", translation: "to do / make" },
  { term: "aller", translation: "to go" },
  { term: "venir", translation: "to come" },
  { term: "voir", translation: "to see" },
  { term: "savoir", translation: "to know (facts)" },
  { term: "connaître", translation: "to know (people/places)" },
  { term: "vouloir", translation: "to want" },
  { term: "pouvoir", translation: "to be able to" },
  { term: "dire", translation: "to say" },
  { term: "parler", translation: "to speak" },
  { term: "manger", translation: "to eat" },
  { term: "boire", translation: "to drink" },
  { term: "acheter", translation: "to buy" },
  { term: "chercher", translation: "to look for" },
  { term: "penser", translation: "to think" },
  { term: "comprendre", translation: "to understand" },
  { term: "apprendre", translation: "to learn" },
  { term: "attendre", translation: "to wait" },
  { term: "aider", translation: "to help" },
  { term: "dormir", translation: "to sleep" },
  { term: "bon", translation: "good" },
  { term: "mauvais", translation: "bad" },
  { term: "grand", translation: "big / tall" },
  { term: "petit", translation: "small" },
  { term: "nouveau", translation: "new" },
  { term: "vieux", translation: "old" },
  { term: "heureux", translation: "happy" },
  { term: "facile", translation: "easy" },
  { term: "difficile", translation: "difficult" },
  { term: "cher", translation: "expensive / dear" },
  { term: "fatigué", translation: "tired" },
  { term: "ici", translation: "here" },
  { term: "là-bas", translation: "over there" },
  { term: "beaucoup", translation: "a lot" },
  { term: "toujours", translation: "always" },
  { term: "jamais", translation: "never" },
  { term: "maintenant", translation: "now" },
  { term: "bonne nuit", translation: "good night", kind: "phrase" },
  { term: "comment ça va ?", translation: "how are you?", kind: "phrase" },
  { term: "je suis désolé", translation: "I'm sorry", kind: "phrase" },
  { term: "pas de problème", translation: "no problem", kind: "phrase" },
  { term: "combien ça coûte ?", translation: "how much does it cost?", kind: "phrase" },
  { term: "je ne comprends pas", translation: "I don't understand", kind: "phrase" },
  { term: "plus lentement, s'il vous plaît", translation: "slower, please", kind: "phrase" },
  { term: "enchanté", translation: "nice to meet you", kind: "phrase" },
  { term: "bonne chance", translation: "good luck", kind: "phrase" },
  { term: "à bientôt", translation: "see you soon", kind: "phrase" },
  { term: "aucune idée", translation: "no idea", kind: "phrase" },
  { term: "ça marche", translation: "that works / okay", kind: "phrase" },
  { term: "truc", translation: "thing / thingy (slang)", kind: "slang" },
  { term: "mec", translation: "guy / dude (slang)", kind: "slang" },
  { term: "bouffer", translation: "to eat (slang)", kind: "slang" },
  { term: "bosser", translation: "to work (slang)", kind: "slang" },
  { term: "génial", translation: "awesome", kind: "slang" },
  { term: "c'est nul", translation: "it sucks (slang)", kind: "slang" },
  { term: "carrément", translation: "totally (slang)", kind: "slang" },
  { term: "t'inquiète", translation: "don't worry (slang)", kind: "slang" },
];

const GERMAN: SeedWord[] = [
  { term: "hallo", translation: "hello" },
  { term: "danke", translation: "thank you" },
  { term: "bitte", translation: "please / you're welcome" },
  { term: "ja", translation: "yes" },
  { term: "nein", translation: "no" },
  { term: "heute", translation: "today" },
  { term: "morgen", translation: "tomorrow / morning" },
  { term: "gestern", translation: "yesterday" },
  { term: "Zeit", translation: "time" },
  { term: "Tag", translation: "day" },
  { term: "Nacht", translation: "night" },
  { term: "Haus", translation: "house" },
  { term: "Arbeit", translation: "work / job" },
  { term: "Wasser", translation: "water" },
  { term: "Essen", translation: "food" },
  { term: "Kaffee", translation: "coffee" },
  { term: "Freund", translation: "friend" },
  { term: "Familie", translation: "family" },
  { term: "Geld", translation: "money" },
  { term: "Stadt", translation: "city" },
  { term: "Straße", translation: "street" },
  { term: "Auto", translation: "car" },
  { term: "Geschäft", translation: "store / business" },
  { term: "Buch", translation: "book" },
  { term: "Mann", translation: "man" },
  { term: "Frau", translation: "woman" },
  { term: "Kind", translation: "child" },
  { term: "Name", translation: "name" },
  { term: "Jahr", translation: "year" },
  { term: "Woche", translation: "week" },
  { term: "Stunde", translation: "hour" },
  { term: "Leben", translation: "life" },
  { term: "Welt", translation: "world" },
  { term: "Sache", translation: "thing" },
  { term: "Hand", translation: "hand" },
  { term: "Herz", translation: "heart" },
  { term: "sein", translation: "to be" },
  { term: "haben", translation: "to have" },
  { term: "machen", translation: "to do / make" },
  { term: "gehen", translation: "to go" },
  { term: "kommen", translation: "to come" },
  { term: "sehen", translation: "to see" },
  { term: "wissen", translation: "to know (facts)" },
  { term: "kennen", translation: "to know (people/places)" },
  { term: "wollen", translation: "to want" },
  { term: "können", translation: "to be able to" },
  { term: "sagen", translation: "to say" },
  { term: "sprechen", translation: "to speak" },
  { term: "essen", translation: "to eat" },
  { term: "trinken", translation: "to drink" },
  { term: "kaufen", translation: "to buy" },
  { term: "suchen", translation: "to look for" },
  { term: "denken", translation: "to think" },
  { term: "verstehen", translation: "to understand" },
  { term: "lernen", translation: "to learn" },
  { term: "warten", translation: "to wait" },
  { term: "helfen", translation: "to help" },
  { term: "schlafen", translation: "to sleep" },
  { term: "gut", translation: "good" },
  { term: "schlecht", translation: "bad" },
  { term: "groß", translation: "big / tall" },
  { term: "klein", translation: "small" },
  { term: "neu", translation: "new" },
  { term: "alt", translation: "old" },
  { term: "glücklich", translation: "happy" },
  { term: "einfach", translation: "easy / simple" },
  { term: "schwer", translation: "hard / heavy" },
  { term: "teuer", translation: "expensive" },
  { term: "müde", translation: "tired" },
  { term: "hier", translation: "here" },
  { term: "dort", translation: "there" },
  { term: "viel", translation: "a lot" },
  { term: "immer", translation: "always" },
  { term: "nie", translation: "never" },
  { term: "jetzt", translation: "now" },
  { term: "guten Morgen", translation: "good morning", kind: "phrase" },
  { term: "gute Nacht", translation: "good night", kind: "phrase" },
  { term: "wie geht's?", translation: "how are you?", kind: "phrase" },
  { term: "es tut mir leid", translation: "I'm sorry", kind: "phrase" },
  { term: "kein Problem", translation: "no problem", kind: "phrase" },
  { term: "was kostet das?", translation: "how much does it cost?", kind: "phrase" },
  { term: "ich verstehe nicht", translation: "I don't understand", kind: "phrase" },
  { term: "langsamer, bitte", translation: "slower, please", kind: "phrase" },
  { term: "freut mich", translation: "nice to meet you", kind: "phrase" },
  { term: "viel Glück", translation: "good luck", kind: "phrase" },
  { term: "bis später", translation: "see you later", kind: "phrase" },
  { term: "keine Ahnung", translation: "no idea", kind: "phrase" },
  { term: "geil", translation: "awesome (slang)", kind: "slang" },
  { term: "krass", translation: "crazy / intense (slang)", kind: "slang" },
  { term: "Quatsch", translation: "nonsense (slang)", kind: "slang" },
  { term: "na ja", translation: "well... (filler)", kind: "slang" },
  { term: "Kohle", translation: "money (slang, lit. coal)", kind: "slang" },
  { term: "passt schon", translation: "it's fine / don't worry (slang)", kind: "slang" },
  { term: "Bock haben", translation: "to feel like doing something (slang)", kind: "slang" },
  { term: "alles klar", translation: "all good / got it", kind: "slang" },
];

const ITALIAN: SeedWord[] = [
  { term: "ciao", translation: "hi / bye" },
  { term: "grazie", translation: "thank you" },
  { term: "per favore", translation: "please" },
  { term: "sì", translation: "yes" },
  { term: "no", translation: "no" },
  { term: "oggi", translation: "today" },
  { term: "domani", translation: "tomorrow" },
  { term: "ieri", translation: "yesterday" },
  { term: "tempo", translation: "time / weather" },
  { term: "giorno", translation: "day" },
  { term: "notte", translation: "night" },
  { term: "casa", translation: "house" },
  { term: "lavoro", translation: "work / job" },
  { term: "acqua", translation: "water" },
  { term: "cibo", translation: "food" },
  { term: "caffè", translation: "coffee" },
  { term: "amico", translation: "friend" },
  { term: "famiglia", translation: "family" },
  { term: "soldi", translation: "money" },
  { term: "città", translation: "city" },
  { term: "strada", translation: "street / road" },
  { term: "macchina", translation: "car" },
  { term: "negozio", translation: "store" },
  { term: "libro", translation: "book" },
  { term: "uomo", translation: "man" },
  { term: "donna", translation: "woman" },
  { term: "bambino", translation: "child" },
  { term: "nome", translation: "name" },
  { term: "anno", translation: "year" },
  { term: "settimana", translation: "week" },
  { term: "ora", translation: "hour / now" },
  { term: "vita", translation: "life" },
  { term: "mondo", translation: "world" },
  { term: "cosa", translation: "thing" },
  { term: "mano", translation: "hand" },
  { term: "cuore", translation: "heart" },
  { term: "essere", translation: "to be" },
  { term: "avere", translation: "to have" },
  { term: "fare", translation: "to do / make" },
  { term: "andare", translation: "to go" },
  { term: "venire", translation: "to come" },
  { term: "vedere", translation: "to see" },
  { term: "sapere", translation: "to know (facts)" },
  { term: "conoscere", translation: "to know (people/places)" },
  { term: "volere", translation: "to want" },
  { term: "potere", translation: "to be able to" },
  { term: "dire", translation: "to say" },
  { term: "parlare", translation: "to speak" },
  { term: "mangiare", translation: "to eat" },
  { term: "bere", translation: "to drink" },
  { term: "comprare", translation: "to buy" },
  { term: "cercare", translation: "to look for" },
  { term: "pensare", translation: "to think" },
  { term: "capire", translation: "to understand" },
  { term: "imparare", translation: "to learn" },
  { term: "aspettare", translation: "to wait" },
  { term: "aiutare", translation: "to help" },
  { term: "dormire", translation: "to sleep" },
  { term: "buono", translation: "good" },
  { term: "cattivo", translation: "bad" },
  { term: "grande", translation: "big" },
  { term: "piccolo", translation: "small" },
  { term: "nuovo", translation: "new" },
  { term: "vecchio", translation: "old" },
  { term: "felice", translation: "happy" },
  { term: "facile", translation: "easy" },
  { term: "difficile", translation: "difficult" },
  { term: "caro", translation: "expensive / dear" },
  { term: "stanco", translation: "tired" },
  { term: "qui", translation: "here" },
  { term: "lì", translation: "there" },
  { term: "molto", translation: "a lot / very" },
  { term: "sempre", translation: "always" },
  { term: "mai", translation: "never" },
  { term: "adesso", translation: "now" },
  { term: "buongiorno", translation: "good morning", kind: "phrase" },
  { term: "buonanotte", translation: "good night", kind: "phrase" },
  { term: "come stai?", translation: "how are you?", kind: "phrase" },
  { term: "mi dispiace", translation: "I'm sorry", kind: "phrase" },
  { term: "nessun problema", translation: "no problem", kind: "phrase" },
  { term: "quanto costa?", translation: "how much does it cost?", kind: "phrase" },
  { term: "non capisco", translation: "I don't understand", kind: "phrase" },
  { term: "più lentamente, per favore", translation: "slower, please", kind: "phrase" },
  { term: "piacere", translation: "nice to meet you", kind: "phrase" },
  { term: "in bocca al lupo", translation: "good luck (lit. 'into the wolf's mouth')", kind: "phrase" },
  { term: "a dopo", translation: "see you later", kind: "phrase" },
  { term: "non ne ho idea", translation: "no idea", kind: "phrase" },
  { term: "figo", translation: "cool (slang)", kind: "slang" },
  { term: "boh", translation: "dunno (slang)", kind: "slang" },
  { term: "dai!", translation: "come on! (slang)", kind: "slang" },
  { term: "che figata", translation: "how cool (slang)", kind: "slang" },
  { term: "magari", translation: "I wish! / maybe", kind: "slang" },
  { term: "tranquillo", translation: "no worries / relax", kind: "slang" },
  { term: "roba", translation: "stuff (slang)", kind: "slang" },
  { term: "che palle", translation: "what a drag (slang)", kind: "slang" },
];

const PORTUGUESE: SeedWord[] = [
  { term: "olá", translation: "hello" },
  { term: "obrigado", translation: "thank you (m; f: obrigada)" },
  { term: "por favor", translation: "please" },
  { term: "sim", translation: "yes" },
  { term: "não", translation: "no" },
  { term: "hoje", translation: "today" },
  { term: "amanhã", translation: "tomorrow" },
  { term: "ontem", translation: "yesterday" },
  { term: "tempo", translation: "time / weather" },
  { term: "dia", translation: "day" },
  { term: "noite", translation: "night" },
  { term: "casa", translation: "house" },
  { term: "trabalho", translation: "work / job" },
  { term: "água", translation: "water" },
  { term: "comida", translation: "food" },
  { term: "café", translation: "coffee" },
  { term: "amigo", translation: "friend" },
  { term: "família", translation: "family" },
  { term: "dinheiro", translation: "money" },
  { term: "cidade", translation: "city" },
  { term: "rua", translation: "street" },
  { term: "carro", translation: "car" },
  { term: "loja", translation: "store" },
  { term: "livro", translation: "book" },
  { term: "homem", translation: "man" },
  { term: "mulher", translation: "woman" },
  { term: "criança", translation: "child" },
  { term: "nome", translation: "name" },
  { term: "ano", translation: "year" },
  { term: "semana", translation: "week" },
  { term: "hora", translation: "hour" },
  { term: "vida", translation: "life" },
  { term: "mundo", translation: "world" },
  { term: "coisa", translation: "thing" },
  { term: "mão", translation: "hand" },
  { term: "coração", translation: "heart" },
  { term: "ser", translation: "to be (essence)" },
  { term: "estar", translation: "to be (state/location)" },
  { term: "ter", translation: "to have" },
  { term: "fazer", translation: "to do / make" },
  { term: "ir", translation: "to go" },
  { term: "vir", translation: "to come" },
  { term: "ver", translation: "to see" },
  { term: "saber", translation: "to know (facts)" },
  { term: "conhecer", translation: "to know (people/places)" },
  { term: "querer", translation: "to want" },
  { term: "poder", translation: "to be able to" },
  { term: "dizer", translation: "to say" },
  { term: "falar", translation: "to speak" },
  { term: "comer", translation: "to eat" },
  { term: "beber", translation: "to drink" },
  { term: "comprar", translation: "to buy" },
  { term: "procurar", translation: "to look for" },
  { term: "pensar", translation: "to think" },
  { term: "entender", translation: "to understand" },
  { term: "aprender", translation: "to learn" },
  { term: "esperar", translation: "to wait / hope" },
  { term: "ajudar", translation: "to help" },
  { term: "dormir", translation: "to sleep" },
  { term: "bom", translation: "good" },
  { term: "mau", translation: "bad" },
  { term: "grande", translation: "big" },
  { term: "pequeno", translation: "small" },
  { term: "novo", translation: "new" },
  { term: "velho", translation: "old" },
  { term: "feliz", translation: "happy" },
  { term: "fácil", translation: "easy" },
  { term: "difícil", translation: "difficult" },
  { term: "caro", translation: "expensive" },
  { term: "cansado", translation: "tired" },
  { term: "aqui", translation: "here" },
  { term: "lá", translation: "there" },
  { term: "muito", translation: "a lot / very" },
  { term: "sempre", translation: "always" },
  { term: "nunca", translation: "never" },
  { term: "agora", translation: "now" },
  { term: "bom dia", translation: "good morning", kind: "phrase" },
  { term: "boa noite", translation: "good night", kind: "phrase" },
  { term: "tudo bem?", translation: "how are you? / all good?", kind: "phrase" },
  { term: "desculpa", translation: "sorry", kind: "phrase" },
  { term: "sem problema", translation: "no problem", kind: "phrase" },
  { term: "quanto custa?", translation: "how much does it cost?", kind: "phrase" },
  { term: "não entendo", translation: "I don't understand", kind: "phrase" },
  { term: "mais devagar, por favor", translation: "slower, please", kind: "phrase" },
  { term: "prazer", translation: "nice to meet you", kind: "phrase" },
  { term: "boa sorte", translation: "good luck", kind: "phrase" },
  { term: "até logo", translation: "see you later", kind: "phrase" },
  { term: "nem ideia", translation: "no idea", kind: "phrase" },
  { term: "legal", translation: "cool (Brazil slang)", kind: "slang" },
  { term: "beleza", translation: "alright / cool (Brazil slang)", kind: "slang" },
  { term: "cara", translation: "dude (Brazil slang)", kind: "slang" },
  { term: "grana", translation: "money (slang)", kind: "slang" },
  { term: "valeu", translation: "thanks / cheers (Brazil slang)", kind: "slang" },
  { term: "massa", translation: "awesome (Brazil slang)", kind: "slang" },
  { term: "fixe", translation: "cool (Portugal slang)", kind: "slang" },
  { term: "tranquilo", translation: "no worries / chill", kind: "slang" },
];

const JAPANESE: SeedWord[] = [
  { term: "こんにちは", translation: "hello", transliteration: "konnichiwa" },
  { term: "ありがとう", translation: "thank you", transliteration: "arigatou" },
  { term: "お願いします", translation: "please", transliteration: "onegaishimasu" },
  { term: "はい", translation: "yes", transliteration: "hai" },
  { term: "いいえ", translation: "no", transliteration: "iie" },
  { term: "今日", translation: "today", transliteration: "kyou" },
  { term: "明日", translation: "tomorrow", transliteration: "ashita" },
  { term: "昨日", translation: "yesterday", transliteration: "kinou" },
  { term: "時間", translation: "time", transliteration: "jikan" },
  { term: "日", translation: "day / sun", transliteration: "hi" },
  { term: "夜", translation: "night", transliteration: "yoru" },
  { term: "家", translation: "house / home", transliteration: "ie" },
  { term: "仕事", translation: "work / job", transliteration: "shigoto" },
  { term: "水", translation: "water", transliteration: "mizu" },
  { term: "食べ物", translation: "food", transliteration: "tabemono" },
  { term: "コーヒー", translation: "coffee", transliteration: "koohii" },
  { term: "友達", translation: "friend", transliteration: "tomodachi" },
  { term: "家族", translation: "family", transliteration: "kazoku" },
  { term: "お金", translation: "money", transliteration: "okane" },
  { term: "町", translation: "town / city", transliteration: "machi" },
  { term: "道", translation: "street / way", transliteration: "michi" },
  { term: "車", translation: "car", transliteration: "kuruma" },
  { term: "店", translation: "store", transliteration: "mise" },
  { term: "本", translation: "book", transliteration: "hon" },
  { term: "男の人", translation: "man", transliteration: "otoko no hito" },
  { term: "女の人", translation: "woman", transliteration: "onna no hito" },
  { term: "子供", translation: "child", transliteration: "kodomo" },
  { term: "名前", translation: "name", transliteration: "namae" },
  { term: "年", translation: "year", transliteration: "toshi" },
  { term: "週間", translation: "week", transliteration: "shuukan" },
  { term: "生活", translation: "life / living", transliteration: "seikatsu" },
  { term: "世界", translation: "world", transliteration: "sekai" },
  { term: "物", translation: "thing", transliteration: "mono" },
  { term: "手", translation: "hand", transliteration: "te" },
  { term: "心", translation: "heart / mind", transliteration: "kokoro" },
  { term: "です", translation: "to be (polite copula)", transliteration: "desu" },
  { term: "ある", translation: "to exist (things)", transliteration: "aru" },
  { term: "いる", translation: "to exist (people/animals)", transliteration: "iru" },
  { term: "する", translation: "to do", transliteration: "suru" },
  { term: "行く", translation: "to go", transliteration: "iku" },
  { term: "来る", translation: "to come", transliteration: "kuru" },
  { term: "見る", translation: "to see / watch", transliteration: "miru" },
  { term: "知る", translation: "to know", transliteration: "shiru" },
  { term: "欲しい", translation: "to want (things)", transliteration: "hoshii" },
  { term: "できる", translation: "to be able to", transliteration: "dekiru" },
  { term: "言う", translation: "to say", transliteration: "iu" },
  { term: "話す", translation: "to speak", transliteration: "hanasu" },
  { term: "食べる", translation: "to eat", transliteration: "taberu" },
  { term: "飲む", translation: "to drink", transliteration: "nomu" },
  { term: "買う", translation: "to buy", transliteration: "kau" },
  { term: "探す", translation: "to look for", transliteration: "sagasu" },
  { term: "思う", translation: "to think", transliteration: "omou" },
  { term: "分かる", translation: "to understand", transliteration: "wakaru" },
  { term: "学ぶ", translation: "to learn", transliteration: "manabu" },
  { term: "待つ", translation: "to wait", transliteration: "matsu" },
  { term: "手伝う", translation: "to help", transliteration: "tetsudau" },
  { term: "寝る", translation: "to sleep", transliteration: "neru" },
  { term: "いい", translation: "good", transliteration: "ii" },
  { term: "悪い", translation: "bad", transliteration: "warui" },
  { term: "大きい", translation: "big", transliteration: "ookii" },
  { term: "小さい", translation: "small", transliteration: "chiisai" },
  { term: "新しい", translation: "new", transliteration: "atarashii" },
  { term: "古い", translation: "old (things)", transliteration: "furui" },
  { term: "嬉しい", translation: "happy / glad", transliteration: "ureshii" },
  { term: "簡単", translation: "easy / simple", transliteration: "kantan" },
  { term: "難しい", translation: "difficult", transliteration: "muzukashii" },
  { term: "高い", translation: "expensive / tall", transliteration: "takai" },
  { term: "疲れた", translation: "tired", transliteration: "tsukareta" },
  { term: "ここ", translation: "here", transliteration: "koko" },
  { term: "そこ", translation: "there", transliteration: "soko" },
  { term: "たくさん", translation: "a lot", transliteration: "takusan" },
  { term: "いつも", translation: "always", transliteration: "itsumo" },
  { term: "今", translation: "now", transliteration: "ima" },
  { term: "おはよう", translation: "good morning", transliteration: "ohayou", kind: "phrase" },
  { term: "おやすみなさい", translation: "good night", transliteration: "oyasuminasai", kind: "phrase" },
  { term: "お元気ですか", translation: "how are you?", transliteration: "ogenki desu ka", kind: "phrase" },
  { term: "すみません", translation: "excuse me / sorry", transliteration: "sumimasen", kind: "phrase" },
  { term: "大丈夫", translation: "it's okay / no problem", transliteration: "daijoubu", kind: "phrase" },
  { term: "いくらですか", translation: "how much is it?", transliteration: "ikura desu ka", kind: "phrase" },
  { term: "分かりません", translation: "I don't understand", transliteration: "wakarimasen", kind: "phrase" },
  { term: "ゆっくりお願いします", translation: "slowly, please", transliteration: "yukkuri onegaishimasu", kind: "phrase" },
  { term: "はじめまして", translation: "nice to meet you", transliteration: "hajimemashite", kind: "phrase" },
  { term: "頑張って", translation: "good luck / do your best", transliteration: "ganbatte", kind: "phrase" },
  { term: "またね", translation: "see you", transliteration: "mata ne", kind: "phrase" },
  { term: "いただきます", translation: "said before eating (bon appétit)", transliteration: "itadakimasu", kind: "phrase" },
  { term: "やばい", translation: "crazy / amazing / awful (slang)", transliteration: "yabai", kind: "slang" },
  { term: "マジで", translation: "seriously? / for real (slang)", transliteration: "maji de", kind: "slang" },
  { term: "うざい", translation: "annoying (slang)", transliteration: "uzai", kind: "slang" },
  { term: "めっちゃ", translation: "super / very (slang)", transliteration: "meccha", kind: "slang" },
  { term: "だるい", translation: "sluggish / can't be bothered (slang)", transliteration: "darui", kind: "slang" },
  { term: "ウケる", translation: "hilarious (slang)", transliteration: "ukeru", kind: "slang" },
  { term: "微妙", translation: "meh / iffy (slang)", transliteration: "bimyou", kind: "slang" },
  { term: "お疲れ", translation: "good work / hey (casual greeting)", transliteration: "otsukare", kind: "slang" },
];

const KOREAN: SeedWord[] = [
  { term: "안녕하세요", translation: "hello", transliteration: "annyeonghaseyo" },
  { term: "감사합니다", translation: "thank you", transliteration: "gamsahamnida" },
  { term: "주세요", translation: "please (give me)", transliteration: "juseyo" },
  { term: "네", translation: "yes", transliteration: "ne" },
  { term: "아니요", translation: "no", transliteration: "aniyo" },
  { term: "오늘", translation: "today", transliteration: "oneul" },
  { term: "내일", translation: "tomorrow", transliteration: "naeil" },
  { term: "어제", translation: "yesterday", transliteration: "eoje" },
  { term: "시간", translation: "time", transliteration: "sigan" },
  { term: "날", translation: "day", transliteration: "nal" },
  { term: "밤", translation: "night", transliteration: "bam" },
  { term: "집", translation: "house / home", transliteration: "jip" },
  { term: "일", translation: "work / job", transliteration: "il" },
  { term: "물", translation: "water", transliteration: "mul" },
  { term: "음식", translation: "food", transliteration: "eumsik" },
  { term: "커피", translation: "coffee", transliteration: "keopi" },
  { term: "친구", translation: "friend", transliteration: "chingu" },
  { term: "가족", translation: "family", transliteration: "gajok" },
  { term: "돈", translation: "money", transliteration: "don" },
  { term: "도시", translation: "city", transliteration: "dosi" },
  { term: "길", translation: "street / way", transliteration: "gil" },
  { term: "차", translation: "car / tea", transliteration: "cha" },
  { term: "가게", translation: "store", transliteration: "gage" },
  { term: "책", translation: "book", transliteration: "chaek" },
  { term: "남자", translation: "man", transliteration: "namja" },
  { term: "여자", translation: "woman", transliteration: "yeoja" },
  { term: "아이", translation: "child", transliteration: "ai" },
  { term: "이름", translation: "name", transliteration: "ireum" },
  { term: "년", translation: "year", transliteration: "nyeon" },
  { term: "주", translation: "week", transliteration: "ju" },
  { term: "인생", translation: "life", transliteration: "insaeng" },
  { term: "세계", translation: "world", transliteration: "segye" },
  { term: "것", translation: "thing", transliteration: "geot" },
  { term: "손", translation: "hand", transliteration: "son" },
  { term: "마음", translation: "heart / mind", transliteration: "maeum" },
  { term: "이다", translation: "to be", transliteration: "ida" },
  { term: "있다", translation: "to exist / have", transliteration: "itda" },
  { term: "하다", translation: "to do", transliteration: "hada" },
  { term: "가다", translation: "to go", transliteration: "gada" },
  { term: "오다", translation: "to come", transliteration: "oda" },
  { term: "보다", translation: "to see / watch", transliteration: "boda" },
  { term: "알다", translation: "to know", transliteration: "alda" },
  { term: "원하다", translation: "to want", transliteration: "wonhada" },
  { term: "말하다", translation: "to speak", transliteration: "malhada" },
  { term: "먹다", translation: "to eat", transliteration: "meokda" },
  { term: "마시다", translation: "to drink", transliteration: "masida" },
  { term: "사다", translation: "to buy", transliteration: "sada" },
  { term: "찾다", translation: "to look for / find", transliteration: "chatda" },
  { term: "생각하다", translation: "to think", transliteration: "saenggakhada" },
  { term: "이해하다", translation: "to understand", transliteration: "ihaehada" },
  { term: "배우다", translation: "to learn", transliteration: "baeuda" },
  { term: "기다리다", translation: "to wait", transliteration: "gidarida" },
  { term: "돕다", translation: "to help", transliteration: "dopda" },
  { term: "자다", translation: "to sleep", transliteration: "jada" },
  { term: "좋다", translation: "good", transliteration: "jota" },
  { term: "나쁘다", translation: "bad", transliteration: "nappeuda" },
  { term: "크다", translation: "big", transliteration: "keuda" },
  { term: "작다", translation: "small", transliteration: "jakda" },
  { term: "새롭다", translation: "new", transliteration: "saeropda" },
  { term: "오래되다", translation: "old (things)", transliteration: "oraedoeda" },
  { term: "행복하다", translation: "happy", transliteration: "haengbokhada" },
  { term: "쉽다", translation: "easy", transliteration: "swipda" },
  { term: "어렵다", translation: "difficult", transliteration: "eoryeopda" },
  { term: "비싸다", translation: "expensive", transliteration: "bissada" },
  { term: "피곤하다", translation: "tired", transliteration: "pigonhada" },
  { term: "여기", translation: "here", transliteration: "yeogi" },
  { term: "거기", translation: "there", transliteration: "geogi" },
  { term: "많이", translation: "a lot", transliteration: "mani" },
  { term: "항상", translation: "always", transliteration: "hangsang" },
  { term: "지금", translation: "now", transliteration: "jigeum" },
  { term: "좋은 아침", translation: "good morning", transliteration: "joeun achim", kind: "phrase" },
  { term: "잘 자요", translation: "good night", transliteration: "jal jayo", kind: "phrase" },
  { term: "어떻게 지내세요?", translation: "how are you?", transliteration: "eotteoke jinaeseyo?", kind: "phrase" },
  { term: "죄송합니다", translation: "I'm sorry", transliteration: "joesonghamnida", kind: "phrase" },
  { term: "괜찮아요", translation: "it's okay / no problem", transliteration: "gwaenchanayo", kind: "phrase" },
  { term: "얼마예요?", translation: "how much is it?", transliteration: "eolmayeyo?", kind: "phrase" },
  { term: "모르겠어요", translation: "I don't know / understand", transliteration: "moreugesseoyo", kind: "phrase" },
  { term: "천천히 말해 주세요", translation: "please speak slowly", transliteration: "cheoncheonhi malhae juseyo", kind: "phrase" },
  { term: "만나서 반가워요", translation: "nice to meet you", transliteration: "mannaseo bangawoyo", kind: "phrase" },
  { term: "화이팅", translation: "good luck / you can do it!", transliteration: "hwaiting", kind: "phrase" },
  { term: "또 봐요", translation: "see you again", transliteration: "tto bwayo", kind: "phrase" },
  { term: "잘 먹겠습니다", translation: "said before eating", transliteration: "jal meokgesseumnida", kind: "phrase" },
  { term: "대박", translation: "awesome / no way (slang)", transliteration: "daebak", kind: "slang" },
  { term: "헐", translation: "OMG / what (slang)", transliteration: "heol", kind: "slang" },
  { term: "진짜", translation: "really / seriously (slang)", transliteration: "jinjja", kind: "slang" },
  { term: "짱", translation: "the best (slang)", transliteration: "jjang", kind: "slang" },
  { term: "아이고", translation: "oh my / oh dear", transliteration: "aigo", kind: "slang" },
  { term: "꿀잼", translation: "super fun (slang)", transliteration: "kkuljaem", kind: "slang" },
  { term: "맛집", translation: "great restaurant (slang)", transliteration: "matjip", kind: "slang" },
  { term: "치맥", translation: "chicken + beer (slang)", transliteration: "chimaek", kind: "slang" },
];

const MANDARIN: SeedWord[] = [
  { term: "你好", translation: "hello", transliteration: "nǐ hǎo" },
  { term: "谢谢", translation: "thank you", transliteration: "xièxie" },
  { term: "请", translation: "please", transliteration: "qǐng" },
  { term: "是", translation: "yes / to be", transliteration: "shì" },
  { term: "不", translation: "no / not", transliteration: "bù" },
  { term: "今天", translation: "today", transliteration: "jīntiān" },
  { term: "明天", translation: "tomorrow", transliteration: "míngtiān" },
  { term: "昨天", translation: "yesterday", transliteration: "zuótiān" },
  { term: "时间", translation: "time", transliteration: "shíjiān" },
  { term: "天", translation: "day / sky", transliteration: "tiān" },
  { term: "晚上", translation: "evening / night", transliteration: "wǎnshang" },
  { term: "家", translation: "home / family", transliteration: "jiā" },
  { term: "工作", translation: "work / job", transliteration: "gōngzuò" },
  { term: "水", translation: "water", transliteration: "shuǐ" },
  { term: "食物", translation: "food", transliteration: "shíwù" },
  { term: "咖啡", translation: "coffee", transliteration: "kāfēi" },
  { term: "朋友", translation: "friend", transliteration: "péngyou" },
  { term: "家人", translation: "family (members)", transliteration: "jiārén" },
  { term: "钱", translation: "money", transliteration: "qián" },
  { term: "城市", translation: "city", transliteration: "chéngshì" },
  { term: "路", translation: "road / street", transliteration: "lù" },
  { term: "车", translation: "car / vehicle", transliteration: "chē" },
  { term: "商店", translation: "store", transliteration: "shāngdiàn" },
  { term: "书", translation: "book", transliteration: "shū" },
  { term: "男人", translation: "man", transliteration: "nánrén" },
  { term: "女人", translation: "woman", transliteration: "nǚrén" },
  { term: "孩子", translation: "child", transliteration: "háizi" },
  { term: "名字", translation: "name", transliteration: "míngzi" },
  { term: "年", translation: "year", transliteration: "nián" },
  { term: "星期", translation: "week", transliteration: "xīngqī" },
  { term: "生活", translation: "life", transliteration: "shēnghuó" },
  { term: "世界", translation: "world", transliteration: "shìjiè" },
  { term: "东西", translation: "thing / stuff", transliteration: "dōngxi" },
  { term: "手", translation: "hand", transliteration: "shǒu" },
  { term: "心", translation: "heart", transliteration: "xīn" },
  { term: "有", translation: "to have / there is", transliteration: "yǒu" },
  { term: "做", translation: "to do / make", transliteration: "zuò" },
  { term: "去", translation: "to go", transliteration: "qù" },
  { term: "来", translation: "to come", transliteration: "lái" },
  { term: "看", translation: "to see / look", transliteration: "kàn" },
  { term: "知道", translation: "to know", transliteration: "zhīdào" },
  { term: "要", translation: "to want / will", transliteration: "yào" },
  { term: "能", translation: "to be able to", transliteration: "néng" },
  { term: "说", translation: "to say / speak", transliteration: "shuō" },
  { term: "吃", translation: "to eat", transliteration: "chī" },
  { term: "喝", translation: "to drink", transliteration: "hē" },
  { term: "买", translation: "to buy", transliteration: "mǎi" },
  { term: "找", translation: "to look for", transliteration: "zhǎo" },
  { term: "想", translation: "to think / want / miss", transliteration: "xiǎng" },
  { term: "懂", translation: "to understand", transliteration: "dǒng" },
  { term: "学", translation: "to learn / study", transliteration: "xué" },
  { term: "等", translation: "to wait", transliteration: "děng" },
  { term: "帮", translation: "to help", transliteration: "bāng" },
  { term: "睡觉", translation: "to sleep", transliteration: "shuìjiào" },
  { term: "好", translation: "good", transliteration: "hǎo" },
  { term: "坏", translation: "bad", transliteration: "huài" },
  { term: "大", translation: "big", transliteration: "dà" },
  { term: "小", translation: "small", transliteration: "xiǎo" },
  { term: "新", translation: "new", transliteration: "xīn" },
  { term: "旧", translation: "old (things)", transliteration: "jiù" },
  { term: "开心", translation: "happy", transliteration: "kāixīn" },
  { term: "容易", translation: "easy", transliteration: "róngyì" },
  { term: "难", translation: "difficult", transliteration: "nán" },
  { term: "贵", translation: "expensive", transliteration: "guì" },
  { term: "累", translation: "tired", transliteration: "lèi" },
  { term: "这里", translation: "here", transliteration: "zhèlǐ" },
  { term: "那里", translation: "there", transliteration: "nàlǐ" },
  { term: "很多", translation: "a lot", transliteration: "hěn duō" },
  { term: "总是", translation: "always", transliteration: "zǒngshì" },
  { term: "现在", translation: "now", transliteration: "xiànzài" },
  { term: "早上好", translation: "good morning", transliteration: "zǎoshang hǎo", kind: "phrase" },
  { term: "晚安", translation: "good night", transliteration: "wǎn'ān", kind: "phrase" },
  { term: "你好吗?", translation: "how are you?", transliteration: "nǐ hǎo ma?", kind: "phrase" },
  { term: "对不起", translation: "I'm sorry", transliteration: "duìbuqǐ", kind: "phrase" },
  { term: "没问题", translation: "no problem", transliteration: "méi wèntí", kind: "phrase" },
  { term: "多少钱?", translation: "how much money?", transliteration: "duōshao qián?", kind: "phrase" },
  { term: "我不懂", translation: "I don't understand", transliteration: "wǒ bù dǒng", kind: "phrase" },
  { term: "请说慢一点", translation: "please speak slower", transliteration: "qǐng shuō màn yīdiǎn", kind: "phrase" },
  { term: "很高兴认识你", translation: "nice to meet you", transliteration: "hěn gāoxìng rènshi nǐ", kind: "phrase" },
  { term: "加油", translation: "good luck / keep going!", transliteration: "jiāyóu", kind: "phrase" },
  { term: "再见", translation: "goodbye", transliteration: "zàijiàn", kind: "phrase" },
  { term: "不好意思", translation: "excuse me / sorry (mild)", transliteration: "bù hǎoyìsi", kind: "phrase" },
  { term: "牛", translation: "awesome (slang, lit. 'cow')", transliteration: "niú", kind: "slang" },
  { term: "帅", translation: "handsome / cool (slang)", transliteration: "shuài", kind: "slang" },
  { term: "哇塞", translation: "wow (slang)", transliteration: "wāsài", kind: "slang" },
  { term: "没事儿", translation: "no big deal (slang)", transliteration: "méishìr", kind: "slang" },
  { term: "随便", translation: "whatever / anything works", transliteration: "suíbiàn", kind: "slang" },
  { term: "吃货", translation: "foodie (slang)", transliteration: "chīhuò", kind: "slang" },
  { term: "土豪", translation: "rich show-off (slang)", transliteration: "tǔháo", kind: "slang" },
  { term: "厉害", translation: "impressive / awesome", transliteration: "lìhai", kind: "slang" },
];

const RUSSIAN: SeedWord[] = [
  { term: "привет", translation: "hi", transliteration: "privet" },
  { term: "спасибо", translation: "thank you", transliteration: "spasibo" },
  { term: "пожалуйста", translation: "please / you're welcome", transliteration: "pozhaluysta" },
  { term: "да", translation: "yes", transliteration: "da" },
  { term: "нет", translation: "no", transliteration: "net" },
  { term: "сегодня", translation: "today", transliteration: "segodnya" },
  { term: "завтра", translation: "tomorrow", transliteration: "zavtra" },
  { term: "вчера", translation: "yesterday", transliteration: "vchera" },
  { term: "время", translation: "time", transliteration: "vremya" },
  { term: "день", translation: "day", transliteration: "den'" },
  { term: "ночь", translation: "night", transliteration: "noch'" },
  { term: "дом", translation: "house / home", transliteration: "dom" },
  { term: "работа", translation: "work / job", transliteration: "rabota" },
  { term: "вода", translation: "water", transliteration: "voda" },
  { term: "еда", translation: "food", transliteration: "yeda" },
  { term: "кофе", translation: "coffee", transliteration: "kofe" },
  { term: "друг", translation: "friend", transliteration: "drug" },
  { term: "семья", translation: "family", transliteration: "sem'ya" },
  { term: "деньги", translation: "money", transliteration: "den'gi" },
  { term: "город", translation: "city", transliteration: "gorod" },
  { term: "улица", translation: "street", transliteration: "ulitsa" },
  { term: "машина", translation: "car", transliteration: "mashina" },
  { term: "магазин", translation: "store", transliteration: "magazin" },
  { term: "книга", translation: "book", transliteration: "kniga" },
  { term: "мужчина", translation: "man", transliteration: "muzhchina" },
  { term: "женщина", translation: "woman", transliteration: "zhenshchina" },
  { term: "ребёнок", translation: "child", transliteration: "rebyonok" },
  { term: "имя", translation: "name", transliteration: "imya" },
  { term: "год", translation: "year", transliteration: "god" },
  { term: "неделя", translation: "week", transliteration: "nedelya" },
  { term: "жизнь", translation: "life", transliteration: "zhizn'" },
  { term: "мир", translation: "world / peace", transliteration: "mir" },
  { term: "вещь", translation: "thing", transliteration: "veshch'" },
  { term: "рука", translation: "hand / arm", transliteration: "ruka" },
  { term: "сердце", translation: "heart", transliteration: "serdtse" },
  { term: "быть", translation: "to be", transliteration: "byt'" },
  { term: "есть (иметь)", translation: "there is / to have", transliteration: "yest'" },
  { term: "делать", translation: "to do / make", transliteration: "delat'" },
  { term: "идти", translation: "to go (on foot)", transliteration: "idti" },
  { term: "приходить", translation: "to come", transliteration: "prikhodit'" },
  { term: "видеть", translation: "to see", transliteration: "videt'" },
  { term: "знать", translation: "to know", transliteration: "znat'" },
  { term: "хотеть", translation: "to want", transliteration: "khotet'" },
  { term: "мочь", translation: "to be able to", transliteration: "moch'" },
  { term: "говорить", translation: "to speak / say", transliteration: "govorit'" },
  { term: "есть (кушать)", translation: "to eat", transliteration: "yest' (kushat')" },
  { term: "пить", translation: "to drink", transliteration: "pit'" },
  { term: "покупать", translation: "to buy", transliteration: "pokupat'" },
  { term: "искать", translation: "to look for", transliteration: "iskat'" },
  { term: "думать", translation: "to think", transliteration: "dumat'" },
  { term: "понимать", translation: "to understand", transliteration: "ponimat'" },
  { term: "учить", translation: "to learn / teach", transliteration: "uchit'" },
  { term: "ждать", translation: "to wait", transliteration: "zhdat'" },
  { term: "помогать", translation: "to help", transliteration: "pomogat'" },
  { term: "спать", translation: "to sleep", transliteration: "spat'" },
  { term: "хороший", translation: "good", transliteration: "khoroshiy" },
  { term: "плохой", translation: "bad", transliteration: "plokhoy" },
  { term: "большой", translation: "big", transliteration: "bol'shoy" },
  { term: "маленький", translation: "small", transliteration: "malen'kiy" },
  { term: "новый", translation: "new", transliteration: "novyy" },
  { term: "старый", translation: "old", transliteration: "staryy" },
  { term: "счастливый", translation: "happy", transliteration: "schastlivyy" },
  { term: "лёгкий", translation: "easy / light", transliteration: "lyogkiy" },
  { term: "трудный", translation: "difficult", transliteration: "trudnyy" },
  { term: "дорогой", translation: "expensive / dear", transliteration: "dorogoy" },
  { term: "усталый", translation: "tired", transliteration: "ustalyy" },
  { term: "здесь", translation: "here", transliteration: "zdes'" },
  { term: "там", translation: "there", transliteration: "tam" },
  { term: "много", translation: "a lot", transliteration: "mnogo" },
  { term: "всегда", translation: "always", transliteration: "vsegda" },
  { term: "сейчас", translation: "now", transliteration: "seychas" },
  { term: "доброе утро", translation: "good morning", transliteration: "dobroye utro", kind: "phrase" },
  { term: "спокойной ночи", translation: "good night", transliteration: "spokoynoy nochi", kind: "phrase" },
  { term: "как дела?", translation: "how are you?", transliteration: "kak dela?", kind: "phrase" },
  { term: "извините", translation: "excuse me / sorry", transliteration: "izvinite", kind: "phrase" },
  { term: "нет проблем", translation: "no problem", transliteration: "net problem", kind: "phrase" },
  { term: "сколько это стоит?", translation: "how much does it cost?", transliteration: "skol'ko eto stoit?", kind: "phrase" },
  { term: "я не понимаю", translation: "I don't understand", transliteration: "ya ne ponimayu", kind: "phrase" },
  { term: "помедленнее, пожалуйста", translation: "slower, please", transliteration: "pomedlenneye, pozhaluysta", kind: "phrase" },
  { term: "очень приятно", translation: "nice to meet you", transliteration: "ochen' priyatno", kind: "phrase" },
  { term: "удачи", translation: "good luck", transliteration: "udachi", kind: "phrase" },
  { term: "до встречи", translation: "see you", transliteration: "do vstrechi", kind: "phrase" },
  { term: "понятия не имею", translation: "no idea", transliteration: "ponyatiya ne imeyu", kind: "phrase" },
  { term: "круто", translation: "cool (slang)", transliteration: "kruto", kind: "slang" },
  { term: "классно", translation: "awesome (slang)", transliteration: "klassno", kind: "slang" },
  { term: "блин", translation: "darn (mild slang, lit. 'pancake')", transliteration: "blin", kind: "slang" },
  { term: "ничего себе", translation: "wow / no way (slang)", transliteration: "nichego sebe", kind: "slang" },
  { term: "давай", translation: "come on / let's go / bye (slang)", transliteration: "davay", kind: "slang" },
  { term: "норм", translation: "fine / okay (slang)", transliteration: "norm", kind: "slang" },
  { term: "тусоваться", translation: "to hang out / party (slang)", transliteration: "tusovat'sya", kind: "slang" },
  { term: "бабки", translation: "money (slang)", transliteration: "babki", kind: "slang" },
];

export const WORD_LISTS: Record<string, SeedWord[]> = {
  he: HEBREW,
  es: SPANISH,
  fr: FRENCH,
  de: GERMAN,
  it: ITALIAN,
  pt: PORTUGUESE,
  ja: JAPANESE,
  ko: KOREAN,
  zh: MANDARIN,
  ru: RUSSIAN,
};
